# Generated by Django 4.0.7 on 2023-06-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_body_alter_comment_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
